version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://itinerary_user:itinerary_password@db:5432/itinerary_db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: itinerary_user
      POSTGRES_PASSWORD: itinerary_password
      POSTGRES_DB: itinerary_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
